### ISSUE TITLE
Folder text box shows only some characters behind

### ISSUE THREAD

**Issue by Charltsing** [Willy-Kimura/BetterFolderBrowser#1]
open BetterFolderBrowser-->select directory -->close
reopen BetterFolderBrowser ,Folder text box shows only some characters behind

<img width="823" height="518" alt="Image" src="https://github.com/user-attachments/assets/c0113cbe-6765-468b-956e-cd7c513cb7be" />

**Comment by Willy-Kimura** [comment]
The linked resource seems to be restricted... Please re-upload and share.

However, I tried this and tested and it seems to be working perfectly fine.
Which Windows version are you using?

**Comment by Willy-Kimura** [comment]
Seen it. That's really not a bug. 
Usually when you select long paths, the last part (often the folder name) is highlighted and brought to the fore while the other part is hidden, but can be shown whenever you highlight and drag the cursor to the left.

**Comment by Charltsing** [comment]
Is there any way to see the full path without dragging it?

**Comment by Willy-Kimura** [comment]
None I've found yet. That's tied to how Windows displays selected extended texts in inputs.

**Comment by Charltsing** [comment]
两种可能：

1、这是 Windows 原生控件的行为，不是 C# 或 .NET 的问题。
OpenFileDialog 实际上是封装了 Windows 的 通用文件对话框（Common File Dialog） ，它的文件名输入框（Edit 控件）在 某些版本的中文 Windows 系统 中，对中文等宽字符的显示长度有限制，默认只显示最后 7 个汉字，或者14个英文字符。

2、vista新对话框的编辑框（ComboBoxEx32 + Edit）在“初始设置”时，内部同样会按“平均字符宽度”做一次性滚动，把超出可视长度的部分向左隐藏掉；它并没有自动把光标滚到最左侧。换句话说——文字没有被截断，只是被向左卷动了，和旧对话框的 bug 表象一致，但机制不同。
