### ISSUE TITLE
.NET7.0 Support?

### ISSUE THREAD

**Issue by MCcber** [Willy-Kimura/BetterFolderBrowser#10]
Can this package run in a .NET7.0 project? ShowDialog method must cause a null reference exception

**Comment by shivaprasadms** [comment]
I got null reference exception when i tried on my wpf .net 6 project at showdialog

**Comment by MCcber** [comment]
> I got null reference exception when i tried on my wpf .net 6 project at showdialog

I feel like this package was abandoned by the author, it was last updated three years ago
