### ISSUE TITLE
Add custom control

### ISSUE THREAD

**Issue by E-Mans-Application** [Willy-Kimura/BetterFolderBrowser#3]
Hello,

First of all I would like to thank you for making available a so useful component, it is extremely nicer to use than the default .NET FolderBrowserDialog.

I would need to add a custom control (button, checkbox, linklabel, etc.) left to the "open" button. 
Here is an example of what I would like to achieve, from Microsoft Office Word's file dialog: https://www.casimages.com/i/200521025636307977.png.html
The dialog is very similar to the default file dialog, but there is a custom "Tools" menu. Moreover, the "open" button itslef has a dropdown menu, which could be useful as well.

I could create a custom Windows Form but I am very attached to the appearance and to the behaviour of the default dialog.

Casting an eye over your source code and the .NET Framework one, I found methods to set a custom text of your choice to the Open button, or to the "file name" label, but I found nothing to add a control. (https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/AppModel/ShellProvider.cs,569)

I found code examples to "stick" a user control next to the dialog by overriding WndProc, but the user control is put at bottom or at right of the dialog, not "inside" the dialog.

As I guess you must have studied the native .NET file dialog code for implementing your browser, I was wondering whether you would know a way to solve my issue.

Thanks in advance,
E__Man.

**Comment by E-Mans-Application** [comment]
I have finally found a way: https://social.msdn.microsoft.com/Forums/fr-FR/dc29095d-7403-4874-8f57-80a2e3cd4057/utiliser-ifiledialogcustomize-en-vbnet?forum=vbasicfr, but this requires Interop.

**Comment by Willy-Kimura** [comment]
Hello @E-Mans-Application 

I'm happy that this nice little library has been of great use to you! It's for people like you that I do what I do...

That's a good use case, but will require additional P/Invokes and may eventually deviate from the current design of the library. I checked the link and saw it pretty much achieves just that. Glad you went on ahead to find a solution for it. Much appreciated.

I'll definitely look into this and see what I can do at the very least.

Best regards, WK.
