### ISSUE TITLE
AllowMultiselect

### ISSUE THREAD

**Issue by silverfrost** [Willy-Kimura/BetterFolderBrowser#4]
Is the BetterFolderBrowserDialog.AllowMultiselect property correct? allow_multiselect is private and never assigned.

        public bool AllowMultiselect
        {
            get { return allow_multiselect; }
            set { ofd.Multiselect = value; }
        }

**Comment by Willy-Kimura** [comment]
Great thanks @silverfrost

**Comment by eltos** [comment]
@Willy-Kimura why closing the issue when the fixing PR #5 is still open?
