### ISSUE TITLE
What license is it under?

### ISSUE THREAD

**Issue by genesistoxical** [Willy-Kimura/BetterFolderBrowser#8]
Hello!

 I would like to use your library, it is really very useful. However, I would like to clarify a doubt before making use of it:

*nuget.org* shows that **BetterFolderBrowser** is under the **MIT license**, but there is no license here. Is it really under the **MIT license**?

Thanks.

**Comment by Willy-Kimura** [comment]
Hi!

Yes indeed, it's under the MIT license. I've also included the license file in the repo for reference.
